development:
    sessions:
        default:
            database: booking_dev
            hosts:
                - 54.191.28.113:27017
            #username: 3z3subu
            #password: cu4lqu13r4
production:
    sessions:
        default:
            default:
            database: booking
            hosts:
                - 54.191.28.113:27017
            #username: "siteUserAdmin"
            #password: "password"        
